title: Power Pages Pro - 3PM
description: An open resource for Power Pages Project Management
theme: just-the-docs

url: https://tinorabe.github.io/3pm

aux_links:

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.0"
